http:
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecLapiScheme: "http"
          crowdsecLapiKey: "${CROWDSEC_BOUNCER_KEY}"
          crowdsecMode: "stream"${CROWDSEC_APPSEC_PLUGIN_BLOCK}

    security-chain:
      chain:
        middlewares: [crowdsec]
