http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec-bouncer:
          enabled: true
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecLapiScheme: "http"
          crowdsecLapiKey: "${CROWDSEC_BOUNCER_KEY}"
          crowdsecMode: "live"

    security-chain:
      chain:
        middlewares:
          - crowdsec
