http:
  routers:
    traefik:
      rule: "Host(`${TRAEFIK_HOST}`)"
      entryPoints:
        - websecure
      service: api@internal
${TRAEFIK_PUBLIC_MIDDLEWARES_BLOCK}
      tls:
        certResolver: letsencrypt
