http:
  routers:
    traefik:
      rule: "Host(`${TRAEFIK_HOST}`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares: ${TRAEFIK_PUBLIC_MIDDLEWARES}
      tls:
        certResolver: letsencrypt
