http:
  routers:
    traefik:
      rule: "Host(`${TRAEFIK_HOST}`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - oauth2-chain
      tls:
        certResolver: letsencrypt
