api:
  dashboard: true

accessLog:
  filePath: /logs/access.log
  format: json

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs: ${TRAEFIK_TRUSTED_IPS_YAML}
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs: ${TRAEFIK_TRUSTED_IPS_YAML}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: ${NETWORK_NAME}
  file:
    directory: /dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

experimental:
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.6.0"
