services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "TZ=${TZ_VALUE}"
      - "CF_API_EMAIL=${CF_API_EMAIL}"
      - "CF_API_KEY=${CF_API_KEY}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./dynamic:/dynamic:ro"
      - "./acme:/acme"

networks:
  proxy:
    name: ${NETWORK_NAME}
    external: true
